version: '3'
services:
  el_1:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.2.1"
    volumes:
      - /.elastic:/.elastic
    environment:
     - cluster.name=my_cluster
     - node.name=el_1
     - discovery.zen.ping.unicast.hosts=el_1,el_2,el_3
     - discovery.zen.minimum_master_nodes=2
  el_2:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.2.1"
    volumes:
      - /.elastic:/.elastic
    environment:
     - cluster.name=my_cluster
     - node.name=el_2
     - discovery.zen.ping.unicast.hosts=[el_1,el_2]
     - discovery.zen.minimum_master_nodes=2
  el_3:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.2.1"
    volumes:
      - /.elastic:/.elastic
    environment:
     - cluster.name=my_cluster
     - node.name=el_3
     - discovery.zen.ping.unicast.hosts=el_1,el_2,el_3
     - discovery.zen.minimum_master_nodes=2
  kibana:
    image: "docker.elastic.co/kibana/kibana:6.2.1"
    ports:
      - "5601:5601"
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_URL=http://el_1:9200
    depends_on:
      - el_1
      - el_2
      - el_3
      - web
  web:
    build: .
    volumes:
     - /.docker/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
     - "8080:80"
    environment:
     - NGINX_PORT=80
    depends_on:
      - el_1
      - el_2
      - el_3
